// 更新用户信息
const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

// 更新当前播放的音乐信息
const UPDATE_CURRENT_PLAY = 'UPDATE_CURRENT_PLAY';

const UPDATE_CURRENT_PLAY_LIST = 'UPDATE_CURRENT_PLAY_LIST';

export {
  UPDATE_USER_INFO,
  UPDATE_CURRENT_PLAY_LIST,
  UPDATE_CURRENT_PLAY,
}