// 更新用户信息
const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

// 更新当前播放的音乐信息
const UPDATE_CURRENT_PLAY = 'UPDATE_CURRENT_PLAY';

// 更新当前播放列表
const UPDATE_CURRENT_PLAY_LIST = 'UPDATE_CURRENT_PLAY_LIST';

// 更新当前音乐进度
const UPDATE_CURRENT_TIME = 'UPDATE_CURRENT_TIME';

export {
  UPDATE_USER_INFO,
  UPDATE_CURRENT_PLAY_LIST,
  UPDATE_CURRENT_PLAY,
  UPDATE_CURRENT_TIME,
}