// 更新用户信息
const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
// 更新 每日推荐歌单
const UPDATE_DAILY_PLAYLIST = 'UPDATE_DAILY_PLAYLIST';

// 更新当前播放的音乐信息
const UPDATE_CURRENT_PLAY = 'UPDATE_CURRENT_PLAY';

export {
  UPDATE_USER_INFO,
  UPDATE_DAILY_PLAYLIST,
  UPDATE_CURRENT_PLAY,
}